# Generated by Django 5.0.3 on 2024-04-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procrastinate', '0006_uploads_knowledge_graph_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='topic_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
